trigger:
  branches:
    include:
    - master
  paths:
    include:
    - local-exec-az-cli/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  displayName: 'Copy files to'
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/local-exec-az-cli
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
